name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
      
jobs:
  deploy:
    runs-on: aws-ec2
    steps:
      - name: Pull docker image from Docker Hub
        run: |
          docker pull terabuild/hellobook-backend:latest
      - name: Stop and remove existing container
        run: |
          docker stop hellobook-backend || true
          docker rm -f hellobook-backend || true
      - name: Run new container
        run: |
          docker run -d \
            --name hellobook-backend \
            -p 4000:4000 \
            -e NODE_ENV=production \
            -e PORT=4000 \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -e DATABASE_TYPE=${{ secrets.DATABASE_TYPE }} \
            -e HEALTHCHECK_URL=${{ secrets.HEALTHCHECK_URL }} \
            terabuild/hellobook-backend:latest