name: Push Docker image to Docker Hub

on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build docker image
        run: |
          docker build . -t terabuild/hellobook-backend:latest
      - name: Push docker image
        run: |
          docker push terabuild/hellobook-backend:latest
