name: CI Pipeline

on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Build docker image
        run: |
          docker build . -t terabuild/hellobook-backend:latest
      - name: Push docker image
        run: |
          docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" -p "${{ secrets.DOCKER_HUB_TOKEN }}"
          docker push terabuild/hellobook-backend:latest
          